name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.1.0]

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundler
        run: gem install bundler

      - name: Install gems
        run: |
          bundle config set --local without benchmark
          bundle install --jobs=3

      - name: Rubocop
        run: bundle exec rubocop

      - name: Tests
        run: bundle exec rspec

      # TODO: Fix parsing error on ./coverage/lcov.info (gem version?)
      # Error:  "2022-02-18T11:31:45.593Z"  'error from lcovParse: ' 'Failed to parse string'
      # - name: Coveralls GitHub Action
      #   uses: coverallsapp/github-action@1.1.3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
